# Конфигурация докера, все данные получаем из database.properties файла,
# поэтому здесь ничего указывать не нужно, кроме порта и версии БД
services:
  db:
    image: postgres:latest
    env_file:
      - configs/database.properties
    ports:
      - "5432:5432"